apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  selector:
    matchLabels:
      app: dotnovi
  template:
    metadata:
      labels:
        app: dotnovi
    spec:
      containers:
          ports: